<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-RV54SM4" name="com.TestNG.SamplePackage.Dependencies" tests="9" failures="0" timestamp="26 Jan 2020 07:53:34 GMT" time="0.023" errors="1">
  <testcase name="test8" time="0.000" classname="com.TestNG.SamplePackage.Dependencies"/>
  <testcase name="test1" time="0.015" classname="com.TestNG.SamplePackage.Dependencies">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.TestNG.SamplePackage.Dependencies.test1(Dependencies.java:8)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test1 -->
  <testcase name="test3" time="0.004" classname="com.TestNG.SamplePackage.Dependencies"/>
  <testcase name="test2" time="0.000" classname="com.TestNG.SamplePackage.Dependencies">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.002" classname="com.TestNG.SamplePackage.Dependencies"/>
  <testcase name="test7" time="0.000" classname="com.TestNG.SamplePackage.Dependencies"/>
  <testcase name="test6" time="0.000" classname="com.TestNG.SamplePackage.Dependencies"/>
  <testcase name="test5" time="0.002" classname="com.TestNG.SamplePackage.Dependencies"/>
  <testcase name="test9" classname="com.TestNG.SamplePackage.Dependencies">
    <skipped/>
  </testcase> <!-- test9 -->
</testsuite> <!-- com.TestNG.SamplePackage.Dependencies -->
